language: node_js
sudo: false
node_js:
- stable
addons:
  firefox: '42.0'
cache:
  directories:
  - node_modules
before_script:
- npm install web-component-tester bower polylint
- bower install
- bower install -s https://${GH_TOKEN}@github.com/Collaborne/collaborne-build-tools.git
- polylint
- export PATH=$PWD/node_modules/.bin:$PATH
script:
- xvfb-run wct
